server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    druid:
      url: jdbc:mysql://140.143.186.166:3306/clouddemo?&useSSL=false
      username: root
      password: 123456
  cloud:
    zookeeper:
      connect-string: 140.143.186.166:2181


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.project.cloud.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
