server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启动态路由
      routes:
        - id: payment_routh #payment_route 路由的id，没有固定要求，但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路径
          uri: lb://CLOUD-PAYMENT-SERVICE #服务名
          predicates:
            - Path=/payment/get/**  #断言，路径匹配的进行路由
            - After=2020-09-06T01:25:12.455+08:00[Asia/Shanghai] #ZonedDateTime
            #- Before=2020-09-06T01:25:12.455+08:00[Asia/Shanghai]
            #- Between=两个时间段
            #- Cookie=username,reisen
            - Header=X-Request-Id, \d+
            #-Host
            #-Method
            #-Path
            #-Query

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-register: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka